apiVersion: v1
kind: Secret
metadata:
  name: sitrak-cache
  namespace: 1c-web-client-monitors
type: Opaque
stringData:
  ZABBIX_HOST: "zbx-01.sitrak.ru"
  ZABBIX_PORT: "10051"
  ZABBIX_HOSTNAME: "1C Sitrak_Cache"
  TEST_ENDPOINT: "https://1c.sitrak.ru/Sitrak_Cache/en_US/"
  TEST_USER: "test"
  TEST_PASSWORD: "Bi3fa8ta"
  TEST_TIMEOUT: "60000"
