apiVersion: v1
kind: Secret
metadata:
  name: test-bp-sitrak
  namespace: 1c-web-client-monitors
type: Opaque
stringData:
  ZABBIX_HOST: "zbx-01.sitrak.ru"
  ZABBIX_PORT: "10051"
  ZABBIX_HOSTNAME: "1c-healthcheck"
  TEST_ENDPOINT: "https://1c.sitrak.ru/TEST_BP_SITRAK/en_US/"
  TEST_USER: "monitor"
  TEST_PASSWORD: "XgarZPqLjf6vJLm8ZBXQ"
  TEST_TIMEOUT: "60000"
