apiVersion: v1
kind: Secret
metadata:
  name: bp-sitrak
  namespace: 1c-web-client-monitors
type: Opaque
stringData:
  ZABBIX_HOST: "zbx-01.sitrak.ru"
  ZABBIX_PORT: "10051"
  ZABBIX_HOSTNAME: "1C BP_Sitrak"
  TEST_ENDPOINT: "https://1c.sitrak.ru/BP_Sitrak/ru_RU/"
  TEST_USER: "monitoring"
  TEST_PASSWORD: "XgarZPqLjf6vJLm8ZBXQ"
  TEST_TIMEOUT: "60000"
