apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: 1c-web-client-monitors
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiNmNnbWJrYnhuaC1zdWRvIiwicGFzc3dvcmQiOiJnaHBfekJnd1pFV3B2MVU2MkxnY3czcHNKSDNTcmd6VHRFMkRFekRPIn19fQo=
